import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  headerTitle: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
    paddingTop: 16,
    paddingBottom: 16,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: "#f2f2f2",
    elevation: 5,
    borderBottomWidth: 0.5,
    borderColor: "#d9d9d9",
    zIndex: 150,
  },
  textContentTitle: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
  },
  fontTextTitle: {
    fontSize: 16,
    textAlign: "center",
    fontWeight: "bold",
    color: "#000",
  },
  scrollView: {
    position: "absolute",
    top: 35,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#f2f2f2",
  },
  determine: {
    flexDirection: "column",
    textAlign: "center",
    color: "#2679F3",
    fontSize: 16,
    alignSelf: "center",
  },
  contentContainer: {
    flex: 1,
  },
  ContainerForm: {
    flex: 0,
    position: "relative",
    alignItems: "center",
  },
  scrollView: {
    position: "absolute",
    top: 35,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#ffffff",
  },
  formContainer: {
    marginTop: 50,
    paddingLeft: 16,
    paddingRight: 16,
  },
  input: {
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#000",
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: "#fff",
  },
  formRowContainer: {
    paddingRight: 15,
    paddingLeft: 15,
    backgroundColor: "#fff",
  },
  formRowContainer1: {
    backgroundColor: "#fff",
    paddingTop: 20,
    borderBottomColor: "#d9d9d9",
    borderBottomWidth: 1,
  },
  formRowContainer2: {
    marginTop: 20,
    paddingTop: 0,
    paddingBottom: 10,
  },
  formRow1: {
    flex: 0,
    flexShrink: 1,
    flexDirection: "row",
    paddingLeft: 10,
    paddingRight: 10,
  },
  formRow: {
    flex: 0,
    flexShrink: 1,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#fff",
    paddingLeft: 16,
    paddingRight: 16,
  },
  formRowGender: {
    flex: 0,
    flexShrink: 1,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#d9d9d9",
    paddingLeft: 10,
    paddingRight: 10,
  },
  formRow2: {
    flex: 0,
    flexShrink: 1,
    flexDirection: "row",
    paddingLeft: 10,
    paddingRight: 10,
  },
  Cardcontainer: {
    flex: 1,
    padding: 6,
    width: "100%",
    height: undefined,
    backgroundColor: "#FFF",
    elevation: 2,
  },
  formColumn: {
    flex: 1,
    backgroundColor: "#fff",
    paddingTop: 15,
    paddingBottom: 15,
    justifyContent: "center",
  },
  formColumnPicture: {
    flex: 0,
    paddingTop: 15,
    paddingBottom: 15,
    justifyContent: "center",
  },
  formColumn2: {
    flex: 1,
    paddingTop: 15,
    paddingBottom: 15,
    paddingRight: 0,
    alignItems: "flex-end",
  },
  formColumnAlignLeft: {
    textAlign: "left",
    color: "#000",
  },
  formColumnAlignRight: {
    textAlign: "right",
    paddingRight: 6,
  },
  label: {
    color: "#000",
  },
  picture: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: "#d9d9d9",
  },
  buttonContainer2: {
    paddingRight: 15,
    paddingLeft: 15,
    paddingBottom: 15,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingRight: 20,
    paddingLeft: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#f2f2f2",
    backgroundColor: "#fff",
  },
  circle: {
    height: 20,
    width: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#000",
    alignItems: "center",
    justifyContent: "center",
  },
  checkedCircle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#255a8e",
  },
  label: {
    marginBottom: 6,
    color: "#000",
  },
  inputContainer1: {
    borderColor: "#AAAAAA",
    backgroundColor: "rgba(246,246,246,1)",
    borderRadius: 5,
    borderWidth: 1,
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  inputIcon: {
    width: 20,
    height: 20,
    tintColor: "#000",
    marginLeft: 15,
    justifyContent: "center",
  },
  inputs: {
    height: 45,
    marginLeft: 16,
    color: "#000",
    borderBottomColor: "#FFFFFF",
    flex: 1,
    marginTop: 5,
  },
});
export default styles;
