/* eslint-disable prettier/prettier */
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  headerTitle: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
    // height: 50,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 10,
    paddingRight: 10,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    // backgroundColor: '#f2f2f2',
    backgroundColor: "#255a8e",
    elevation: 5,
    borderBottomWidth: 0.5,
    borderColor: "#255a8e",
    zIndex: 150,
  },
  textContentTitle: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    marginRight: 30,
  },
  fontTextTitle: {
    fontSize: 18,
    textAlign: "center",
    fontWeight: "bold",
    color: "#fff",
  },
  formContainer: {
    padding: 30,
    marginTop: 0,
  },
  pictureContainer: {
    flex: 1,
    position: "relative",
    alignItems: "center",
    paddingTop: 16,
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 16,
    elevation: 6,
  },
  label: {
    marginBottom: 6,
    color: "#000",
  },
  label2: {
    marginTop: 12,
    marginBottom: 6,
    color: "#000",
  },
  label3: {
    marginTop: 0,
    marginBottom: 12,
    alignItems: "center",
    textAlign: "center",
    padding: 10,
    color: "#fff",
    backgroundColor: "#000",
  },
  label4: {
    padding: 10,
    color: "#000",
    backgroundColor: "#e3e3e3",
  },
  label5: {
    marginTop: 12,
    marginBottom: 12,
    alignItems: "center",
    textAlign: "center",
    padding: 10,
    color: "#fff",
    backgroundColor: "#000",
  },
  label6: {
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
    paddingBottom: 10,
    color: "#000",
    backgroundColor: "#e3e3e3",
  },
  input: {
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#000",
    borderRadius: 10,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
  },
  select: {
    marginBottom: 20,
    borderColor: "#000",
    backgroundColor: "rgba(246,246,246,1)",
    borderRadius: 5,
    borderWidth: 1,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
  },
  selectLabel: {
    marginBottom: 20,
    paddingTop: 8,
    paddingBottom: 8,
  },
  selectText: {
    alignSelf: "flex-start",
    marginLeft: 16,
    color: "#000",
    borderBottomColor: "#FFFFFF",
    flex: 1,
    marginTop: 16,
    marginBottom: 16,
  },
  errorMsg: {
    color: "#cc0000",
    marginBottom: 12,
  },
  sucessMsg: {
    color: "#6B8E23",
    marginBottom: 10,
  },
  inputContainer1: {
    borderColor: "#AAAAAA",
    backgroundColor: "#fff",
    borderRadius: 5,
    borderWidth: 1,
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  inputContainer2: {
    borderColor: "#AAAAAA",
    backgroundColor: "rgba(246,246,246,1)",
    borderRadius: 5,
    borderWidth: 1,
    marginBottom: 14,
    flexDirection: "row",
    alignItems: "center",
  },
  inputIOS: {
    fontSize: 16,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "gray",
    borderRadius: 4,
    color: "black",
    paddingRight: 30, // to ensure the text is never behind the icon
  },
  inputAndroid: {
    fontSize: 16,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 0.5,
    borderColor: "purple",
    borderRadius: 8,
    color: "black",
    paddingRight: 30, // to ensure the text is never behind the icon
  },
  chooseStatus: {
    borderColor: "#AAAAAA",
    backgroundColor: "rgba(246,246,246,1)",
    borderRadius: 5,
    borderWidth: 1,
    flex: 1,
    marginTop: 10,
    justifyContent: "center",
  },
  formRowContainerGender: {
    paddingTop: 0,
    paddingBottom: 0,
    borderColor: "#AAAAAA",
    backgroundColor: "rgba(246,246,246,1)",
    borderRadius: 5,
    borderWidth: 1,
    marginBottom: 14,
  },
  // inputContainer2: {
  //   borderColor: '#d9d9d9',
  //   backgroundColor: 'rgba(255, 255, 255, 0.4)',
  //   borderRadius: 8,
  //   borderWidth: 1,
  //   marginBottom: 20,
  //   flexDirection: 'row',
  //   alignItems: 'center',
  // },
  inputIcon: {
    width: 20,
    height: 20,
    tintColor: "#000",
    marginLeft: 15,
    justifyContent: "center",
  },
  inputs: {
    height: 45,
    marginLeft: 16,
    color: "#000",
    borderBottomColor: "#FFFFFF",
    flex: 1,
    marginTop: 5,
  },
  visibilityBtn: {
    position: "absolute",
    right: 4,
    padding: 8,
  },
  btnImage: {
    width: 20,
    height: 20,
  },
  btnImageIcon: {
    width: 20,
    height: 20,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 5,
    marginBottom: 0,
    paddingRight: 20,
    paddingLeft: 20,
    paddingBottom: 10,
    paddingTop: 10,
    // borderBottomWidth: 1,
    // borderBottomColor: '#AAAAAA',
    backgroundColor: "rgba(246,246,246,1)",
  },
  buttonContainer1: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#d9d9d9",
  },
  buttonContainer2: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
  },
  circle: {
    height: 20,
    width: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#000",
    alignItems: "center",
    justifyContent: "center",
  },
  checkedCircle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#2679F3",
  },
  contentContainer: {
    flex: 1,
  },
  formRowContainer2: {
    paddingTop: 40,
    paddingBottom: 10,
  },
  formColumn: {
    flex: 1,
    backgroundColor: "#fff",
    paddingTop: 15,
    paddingBottom: 15,
    justifyContent: "center",
  },
  formColumnGender: {
    flex: 1,
    // backgroundColor: '#fff',
    // paddingTop: 15,
    // paddingBottom: 15,
    justifyContent: "center",
  },
  InvoiceContainer: {
    backgroundColor: "#0D2F52",
    marginTop: "auto",
    marginBottom: "auto",
    height: "auto",
    maxHeight: "auto",
    position: "relative",
    flex: 1,
    padding: 20,
  },
  InvoiceWhite: {
    backgroundColor: "white",
    padding: 20,
    marginTop: 20,
    marginBottom: 20,
  },
  buttonText: {
    fontSize: 21,
    color: "rgb(0,122,255)",
  },
  buttonTouchable: {
    padding: 16,
  },
  signature: {
    flex: 4,
    borderColor: "#000033",
    borderWidth: 1,
    height: 300,
    marginTop: 5,
  },
  buttonstyle2: {
    backgroundColor: "rgb(8,194,223)",
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    height: 50,
    paddingLeft: 30,
    paddingRight: 30,
    borderRadius: 0,
    marginTop: 30,
  },
  buttonstyle3: {
    backgroundColor: "rgb(8,194,223)",
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    height: 50,
    paddingLeft: 30,
    paddingRight: 30,
    borderRadius: 0,
  },
  buttonstyle1: {
    backgroundColor: "#255a8e",
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    height: 50,
    borderRadius: 25,
    margin: 0,
  },
  buttonstyle: {
    backgroundColor: "#255a8e",
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    height: 50,
    borderRadius: 25,
    marginTop: 20,
  },
  buttontextstyle: {
    fontSize: 16,
    textAlign: "center",
    color: "#fff",
    fontWeight: "bold",
  },
  buttontextstyle2: {
    fontSize: 14,
    textAlign: "center",
    color: "#fff",
    fontWeight: "bold",
  },
  Cardcontainer: {
    flex: 1,
    padding: 20,
    width: "100%",
    height: undefined,
    backgroundColor: "#FFF",
    elevation: 2,
    textAlign: "center",
    marginTop: 10,
  },
  containerImage: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#AAAAAA",
    backgroundColor: "rgba(246,246,246,1)",
    borderRadius: 5,
    borderWidth: 1,
    // padding: 16,
  },
  inputContainerImg: {
    // borderColor: "#d9d9d9",
    backgroundColor: "rgba(255, 255, 255, 0.4)",
    borderRadius: 0,
    // borderBottomWidth: 1,
    marginBottom: 0,
    flexDirection: "row",
    alignItems: "center",
  },
  footerButton: {
    flexDirection: "row",
    marginLeft: 15,
  },
  footerText: {
    fontSize: 16,
    color: "#FFF",
    textAlign: "center",
  },
  footer: {
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
});
export default styles;
