import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  headerTitle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 10,
    paddingRight: 10,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#f2f2f2',
    elevation: 5,
    borderWidth: 1,
    borderColor: '#d9d9d9',
    zIndex: 150,
  },
  textContentTitle: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    marginRight: 30,
  },
  fontTextTitle: {
    fontSize: 18,
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#000',
  },
  scrollView: {
    position: 'absolute',
    top: 35,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#f2f2f2',
  },
  header: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'flex-start',
    height: 50,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#007aff',
    elevation: 1,
    borderBottomWidth: 0,
  },
  ContainerForm: {
    flex: 0,
    position: 'relative',
    alignItems: 'center',
  },
  contentContainer: {
    flex: 1,
  },
  formRowContainer: {
    paddingRight: 15,
    paddingLeft: 15,
    backgroundColor: '#fff',
  },
  formRowContainer1: {
    paddingTop: 20,
    paddingBottom: 20,
  },
  formRowContainer2: {
    paddingTop: 0,
    paddingBottom: 10,
  },
  formRowContainer3: {
    paddingTop: 10,
    paddingBottom: 10,
  },
  formRow1: {
    flex: 0,
    flexShrink: 1,
    flexDirection: 'row',
    paddingLeft: 10,
    paddingRight: 10,
  },
  selectGender: {
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 5,
    paddingBottom: 5,
  },
  formRow: {
    flex: 0,
    flexShrink: 1,
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
    paddingLeft: 10,
    paddingRight: 10,
  },
  formRowType: {
    flex: 0,
    flexShrink: 1,
    flexDirection: 'row',
    paddingLeft: 10,
    paddingRight: 10,
  },
  formRowGender: {
    flex: 0,
    flexShrink: 1,
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
    paddingLeft: 10,
    paddingRight: 5,
  },
  formRow2: {
    flex: 0,
    flexShrink: 1,
    flexDirection: 'row',
    paddingLeft: 10,
    paddingRight: 10,
  },
  Cardcontainer: {
    flex: 1,
    padding: 6,
    width: '100%',
    height: undefined,
    backgroundColor: '#FFF',
    elevation: 2,
  },
  formColumnlabel: {
    flex: 0,
    paddingTop: 15,
    paddingBottom: 15,
    justifyContent: 'center',
  },

  formColumn: {
    flex: 1,
    paddingTop: 15,
    paddingBottom: 15,
    justifyContent: 'center',
  },

  formColumnParkLabel: {
    flex: 0,
    paddingTop: 15,
    paddingBottom: 15,
    justifyContent: 'center',
  },

  formColumnLabel: {
    flex: 0.5,
    paddingTop: 15,
    paddingBottom: 15,
    justifyContent: 'center',
  },

  formColumnPark: {
    flex: 1,
    paddingTop: 15,
    paddingBottom: 15,
    justifyContent: 'center',
  },

  formColumnPicture: {
    flex: 0,
    paddingTop: 15,
    paddingBottom: 15,
    justifyContent: 'center',
  },
  formColumn2: {
    flex: 1,
    paddingTop: 15,
    paddingBottom: 15,
    paddingRight: 0,
    alignItems: 'flex-end',
  },
  formColumnAlignLeft: {
    textAlign: 'left',
    color: '#000',
  },
  formColumnAlignRight: {
    textAlign: 'right',
    paddingRight: 6,
  },
  label: {
    color: '#000',
  },
  picture: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: '#d9d9d9',
  },
  buttonContainer: {
    paddingRight: 15,
    paddingLeft: 15,
    paddingTop: 15,
    paddingBottom: 15,
  },
  buttonContainer2: {
    paddingRight: 15,
    paddingLeft: 15,
    paddingBottom: 15,
  },
});
export default styles;
