import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  FlatlistContainer: {
    // backgroundColor:'#f2f2f2',
  },
  headerTitle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    height: 50,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    // backgroundColor: '#007aff',
    backgroundColor: '#f2f2f2',
    elevation: 5,
    borderBottomWidth: 1,
    borderColor: '#d9d9d9',
    zIndex: 150,
  },
  textTitle: {
    color: '#000',
    fontSize: 18,
    fontWeight: 'bold',
  },
  listItem: {
    marginBottom: 10,
    padding: 16,
    backgroundColor: '#FFF',
    width: '100%',
    flex: 1,
    alignSelf: 'center',
    borderRadius: 5,
    elevation: 20,
    borderWidth: 1,
    borderColor: '#d9d9d9',
    zIndex: 150,
  },
  header: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'flex-start',
    height: 50,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#007aff',
    // backgroundColor: '#ffffff',
    elevation: 1,
    borderBottomWidth: 0,
  },
  inputs: {
    height: 45,
    marginLeft: 10,
    color: '#000',
    borderBottomColor: '#FFFFFF',
    flex: 1,
    marginTop: 5,
  },
  inputs2: {
    height: 60,
    marginLeft: 10,
    color: '#000',
    borderBottomColor: '#FFFFFF',
    flex: 1,
    marginTop: 5,
  },
  formContainer: {
    padding: 16,
  },
  pictureContainer: {
    flex: 1,
    position: 'relative',
    alignItems: 'center',
    paddingTop: 16,
    paddingBottom: 16,
    elevation: 6,
  },
  label: {
    marginBottom: 6,
    color: '#000',
  },
  input: {
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#d9d9d9',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 10,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
  },
  ContainerForm: {
    flex: 0,
    position: 'relative',
    alignItems: 'center',
  },
  contentContainer: {
    flex: 1,
  },
  formRowContainer: {
    paddingRight: 15,
    paddingLeft: 15,
    backgroundColor: '#fff',
  },
  formRowContainer1: {
    paddingTop: 20,
    paddingBottom: 20,
  },
  formRowContainer2: {
    paddingTop: 0,
    paddingBottom: 10,
  },
  formRow1: {
    flex: 0,
    flexShrink: 1,
    flexDirection: 'row',
    paddingLeft: 10,
    paddingRight: 10,
  },
  selectGender: {
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 5,
    paddingBottom: 5,
  },
  formRow: {
    flex: 0,
    flexShrink: 1,
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
    paddingLeft: 10,
    paddingRight: 10,
  },
  formRowGender: {
    flex: 0,
    flexShrink: 1,
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
    paddingLeft: 10,
    paddingRight: 5,
  },
  Cardcontainer: {
    flex: 1,
    padding: 16,
    width: '100%',
    height: undefined,
    backgroundColor: '#FFF',
    elevation: 2,
    marginTop: 6,
  },
  formColumnParkLabel: {
    flex: 0,
    paddingTop: 15,
    paddingBottom: 15,
    justifyContent: 'center',
  },
  formColumnLabel: {
    flex: 0.5,
    paddingTop: 15,
    paddingBottom: 15,
    justifyContent: 'center',
  },
  formColumnPark: {
    flex: 1,
    paddingTop: 15,
    paddingBottom: 15,
    justifyContent: 'center',
  },
  formColumnPicture: {
    flex: 0,
    paddingTop: 15,
    paddingBottom: 15,
    justifyContent: 'center',
  },
  formColumn2: {
    flex: 1,
    paddingTop: 15,
    paddingBottom: 15,
    paddingRight: 0,
    alignItems: 'flex-end',
  },
  formColumnAlignLeft: {
    textAlign: 'left',
    color: '#000',
  },
  formColumnAlignRight: {
    textAlign: 'right',
    paddingTop: 6,
    paddingRight: 6,
    fontSize: 12,
  },
  picture: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: '#d9d9d9',
  },
  buttonContainer: {
    paddingRight: 15,
    paddingLeft: 15,
    paddingTop: 15,
    paddingBottom: 15,
  },
  buttonContainer2: {
    paddingRight: 15,
    paddingLeft: 15,
    paddingBottom: 15,
  },
  inputContainer1: {
    borderColor: '#d9d9d9',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputContainer2: {
    borderColor: '#d9d9d9',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 20,
    height: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  formRow2: {
    flex: 0,
    flexShrink: 1,
    flexDirection: 'row',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: '#d9d9d9',
    borderBottomColor: '#d9d9d9',
    paddingLeft: 10,
    paddingRight: 10,
  },
  formColumnImage: {
    flexDirection: 'column',
    justifyContent: 'center',
    marginRight: 6,
    marginTop: 6,
  },
  formColumn: {
    flex: 1,
  },
  formColumnAlignRight2: {
    alignContent: 'flex-end',
    alignItems: 'flex-end',
    paddingRight: 6,
  },
  headerTitle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    // height: 50,
    paddingTop: 16,
    paddingBottom: 16,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    //backgroundColor: '#007aff',
    // backgroundColor: '#f2f2f2',
    // backgroundColor: '#fff',
    backgroundColor: '#2679F3',
    elevation: 5,
    borderBottomWidth: 0.5,
    zIndex: 100,
  },
  textTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    padding: 16,
  },
  headerText: {
    padding: 8,
    fontSize: 14,
    color: '#444444',
    textAlign: 'center',
  },
  tabContent: {
    color: '#444444',
    fontSize: 18,
    margin: 24,
  },
  Seperator: {
    marginHorizontal: -10,
    alignSelf: 'stretch',
    borderTopWidth: 1,
    borderTopColor: '#888888',
    marginTop: 24,
  },
  tabStyle: {
    borderColor: '#D52C43',
  },
  activeTabStyle: {
    backgroundColor: '#D52C43',
  },
  card: {
    marginHorizontal: 0,
    backgroundColor: '#fff',
  },
  footer: {
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  root: {
    height: 64,
    backgroundColor: '#00000077',
    alignItems: 'center',
    justifyContent: 'center',
  },
  text: {
    fontSize: 17,
    color: '#FFF',
  },
  footerButton: {
    flexDirection: 'row',
    marginLeft: 15,
  },
  footerText: {
    fontSize: 16,
    color: '#FFF',
    textAlign: 'center',
  },
});
export default styles;
